version: '3.9'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=roles
      - TZ=America/Argentina/Buenos_Aires
      - PGTZ=America/Argentina/Buenos_Aires
    ports:
      - '5433:5432'
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
